
add_subdirectory(cstring_getStatusCodeString)
add_subdirectory(cstring_vector)
add_subdirectory(cstring.borrowed)
if(NOT NO_CSTRING_CPP_API)

	add_subdirectory(cstring.instance)
endif()
add_subdirectory(cstring.insert-replace)


# ############################## end of file ############################# #
